smart_search_homepage:
    path:     /
    defaults: { _controller: SmartSearchSearchBundle:Search:home }

smart_search_ajax_search_engine:
    path:     /ajax/search/{term}
    defaults: { _controller: SmartSearchSearchBundle:Search:ajaxSearchEngine, _format : json }
    requirements:
      _method: GET
    
